Controllers/CustomerController.cs
using DomingoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DomingoApp.Controllers
{
    //(4. Continuation and close off, 2021) and (Dot Net Tutorials, 2021). 
    public class CustomerController : Controller
    {
        CustomerDAL custDAL = new CustomerDAL();    //object to call methods from other models

        //method to show all of the customers information on the web page (get all customer information)
        public IActionResult Index()
        {
            List<CustomerInformation> custInfo = new List<CustomerInformation>();
            custInfo = custDAL.GetAllCustomers().ToList();

            return View(custInfo);
        }

        //create customer
        [HttpGet]       //sends and recieve data between the client and server using the web app
        public IActionResult Create()       //makes the html code visible on the web pages as it returns the view
        {
            return View();
        }

        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]      //provides vailadation for any unsafe HTTP
        public IActionResult Create([Bind] CustomerInformation objcustInfo)
        {
            if (ModelState.IsValid)
            {
                custDAL.CreateCustomer(objcustInfo);
                return RedirectToAction("Create", "Job", new { JobController = "" });
            }

            return View(objcustInfo);
        }



        //customer details
        [Route("Customer/Details/{custID}")]
        [HttpGet]
        public IActionResult Details (int? custID)
        {
            if (custID == null)
            {
                return NotFound();
            }

            CustomerInformation custInfo = custDAL.GetCustomerByID(custID);
            if (custInfo == null)
            {
                return NotFound();
            }
            return View(custInfo);
        }

        //update customer
        [Route("Customer/Update/{custID}")]
        public IActionResult Update(int? custID)
        {
            if (custID == null)
            {
                return NotFound();
            }

            CustomerInformation custInfo = custDAL.GetCustomerByID(custID);
            if (custInfo == null)
            {
                return NotFound();
            }
            return View(custInfo);
        }

        [Route("Customer/Update/{custID}")]
        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]      //provides vailadation for any unsafe HTTP
        public IActionResult Update(int? custID, [Bind] CustomerInformation objcustInfo)
        {
            if (custID == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                custDAL.UpdateCustomer(objcustInfo);
                return RedirectToAction("Index");
            }

            return View(custDAL);
        }

        //delete customer
        [Route("Customer/Delete/{custID}")]
        public IActionResult Delete(int? custID)
        {
            if (custID == null)
            {
                return NotFound();
            }

            CustomerInformation custInfo = custDAL.GetCustomerByID(custID);

            if (custInfo == null)
            {
                return NotFound();
            }

            return View(custInfo);
        }

        //delete
        [Route("Customer/Delete/{custID}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteCust(int? custID)
        {
            custDAL.DeleteCustomer(custID);
            return RedirectToAction("Index");
        }
    }

}

Controllers/InvoiceController.cs
using DomingoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DomingoApp.Controllers
{
    //(4. Continuation and close off, 2021) and (Dot Net Tutorials, 2021). 
    public class InvoiceController : Controller
    {
        InvoiceDAL inDAL = new InvoiceDAL();

        //get all
        public IActionResult Index()
        {
            List<InvoiceInformation> inInfo = new List<InvoiceInformation>();
            inInfo = inDAL.GetAllInvoice().ToList();

            return View(inInfo);
        }

        //create
        [HttpGet]       //sends and recieve data between the client and server using the web app
        public IActionResult Create()       //makes the html code visible on the web pages as it returns the view
        {
            return View();
        }

        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]      //provides vailadation for any unsafe HTTP
        public IActionResult Create([Bind] InvoiceInformation objInInfo)
        {
            if (ModelState.IsValid)
            {
                inDAL.CreateInvoice(objInInfo);
                return RedirectToAction("Index");
            }

            return View(objInInfo);
        }

        //details
        [Route("Invoice/Details/{inID}")]
        [HttpGet]
        public IActionResult Details(int? inID)
        {
            if (inID == null)
            {
                return NotFound();
            }

            List<InvoiceInformation> inInfo = new List<InvoiceInformation>();
            inInfo = inDAL.GetInvoiceByID(inID).ToList();
            if (inInfo == null)
            {
                return NotFound();
            }
            return View(inInfo);
        }


    }
}

Controllers/JobController.cs
using DomingoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DomingoApp.Controllers
{
    //(4. Continuation and close off, 2021) and (Dot Net Tutorials, 2021). 
    public class JobController : Controller
    {
        JobDAL jDAL = new JobDAL();
        public IActionResult Index()
        {
            List<JobInformation> jobInfo = new List<JobInformation>();
            jobInfo = jDAL.GetAllJob().ToList();

            return View(jobInfo);
        }

        //create job card
        [HttpGet]       //sends and recieve data between the client and server using the web app
        public IActionResult Create()       //makes the html code visible on the web pages as it returns the view
        {
            return View();
        }

        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]      //provides vailadation for any unsafe HTTP
        public IActionResult Create([Bind] JobInformation objJobInfo)
        {
            if (ModelState.IsValid)
            {
                jDAL.CreateJob(objJobInfo);
                return RedirectToAction("Create", "Materials", new { MaterialsController = "" });
            }

            return View(objJobInfo);
        }

        //details of job
        [Route("Job/Details/{jobID}")]
        [HttpGet]
        public IActionResult Details(int? jobID)
        {
            if (jobID == null)
            {
                return NotFound();
            }

            JobInformation jobInfo = jDAL.GetJobByID(jobID);
            if (jobInfo == null)
            {
                return NotFound();
            }
            return View(jobInfo);
        }

        //update job
        [Route("Job/Update/{jobID}")]
        public IActionResult Update(int? jobID)
        {
            if (jobID == null)
            {
                return NotFound();
            }

            JobInformation jobInfo = jDAL.GetJobByID(jobID);
            if (jobInfo == null)
            {
                return NotFound();
            }
            return View(jobInfo);
        }

        [Route("Job/Update/{jobID}")]
        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]     //provides vailadation for any unsafe HTTP
        public IActionResult Update(int? jobID, [Bind] JobInformation objJobInfo)
        {
            if (jobID == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                jDAL.UpdateJob(objJobInfo);
                return RedirectToAction("Index");
            }

            return View(jDAL);
        }

        //delete job
        [Route("Job/Delete/{jobID}")]
        public IActionResult Delete(int? jobID)
        {
            if (jobID == null)
            {
                return NotFound();
            }

            JobInformation jobInfo = jDAL.GetJobByID(jobID);

            if (jobInfo == null)
            {
                return NotFound();
            }

            return View(jobInfo);
        }

        //delete
        [Route("Job/Delete/{jobID}")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteJob(int? jobID)
        {
            jDAL.DeleteJob(jobID);
            return RedirectToAction("Index");
        }


    }
}

Controllers/JobTypeController.cs
using DomingoApp.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DomingoApp.Controllers
{
    //(4. Continuation and close off, 2021) and (Dot Net Tutorials, 2021). 
    public class JobTypeController : Controller
    {
        JobTypeDAL jtDAL = new JobTypeDAL();

        public IActionResult Index()
        {
            List<JobTypeInformation> jobTypeInfo = new List<JobTypeInformation>();
            jobTypeInfo = jtDAL.GetAllJobType().ToList();

            return View(jobTypeInfo);
        }

        //update
        [Route("JobType/Update/{jobTypeID}")]
        public IActionResult Update(string jobTypeID)
        {
            if (jobTypeID == null)
            {
                return NotFound();
            }

            JobTypeInformation jobTypeInfo = jtDAL.GetJobTypeByID(jobTypeID);
            if (jobTypeInfo == null)
            {
                return NotFound();
            }
            return View(jobTypeInfo);
        }

        [Route("JobType/Update/{jobTypeID}")]
        [HttpPost]  //this pushes the below method, so it can override any other method
        [ValidateAntiForgeryToken]      //provides vailadation for any unsafe HTTP
        public IActionResult Update(string jobTypeID, [Bind] JobTypeInformation objJobTypeInfo)
        {
            if (jobTypeID == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                jtDAL.UpdateJobType(objJobTypeInfo);
                return RedirectToAction("Index");
            }

            return View(jtDAL);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    @*  (W3schools, 2021) and (Fontsawesome, 2017) *@
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DomingoApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">

    <style>
        .center {
            padding: 10px;
            color: #FA8072;
            text-align: center;
        }

        .navbar {
            width: 100%;
            font-family: Arial;
            background-image: linear-gradient(#D3D3D3, #CA907E, #FA8072);
            overflow: auto;
        }

            .navbar a {
                float: left;
                padding: 12px;
                color: black;
                text-decoration: none;
                font-size: 17px;
            }

                .navbar a:hover {
                    background-color: #FA8072;
                }

        .active {
            background-color: #FA8072;
        }
    </style>
</head>
<body>

    <div class="center">
        <h1 style="text-shadow: 8px 8px 10px black ">Domingo Roof Works</h1>
    </div>


    <div class="navbar">
        <li class="nav-item">
            <a class="active" asp-area="" asp-controller="Home" asp-action="Index"><i class="fa fa-fw fa-home"></i>Home</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Home" asp-action="Privacy"><i class="fa fa-user-secret" aria-hidden="true"></i>Privacy</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Customer" asp-action="Index"><i class="fa fa-fw fa-user"></i>Customer</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Job" asp-action="Index"><i class="fa fa-list-ol" aria-hidden="true"></i>Job</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Materials" asp-action="Index"><i class="fa fa-tasks" aria-hidden="true"></i> Materials</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="JobType" asp-action="Index"><i class="fa fa-briefcase" aria-hidden="true"></i>JobType</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Employee" asp-action="Index"><i class="fa fa-user-circle" aria-hidden="true"></i>Employee</a>
        </li>
        <li class="nav-item">
            <a asp-area="" asp-controller="Invoice" asp-action="Index"><i class="fa fa-credit-card" aria-hidden="true"></i>Invoice</a>
        </li>
    </div>

    <div class="container">
        <main role="main" class="pb-0">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted" style="background-image: linear-gradient(#D3D3D3, #F4ECD6, #FA8072)">
        <div class="container" style=" color: black; text-align:left">
            &copy; 2021 - DomingoApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>